/****** Object:  StoredProcedure [dbo].[CREATE_FINANCIAL_PROMOTION_PR]    Script Date: 7/7/2025 3:16:54 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[CREATE_FINANCIAL_PROMOTION_PR]
    @P_FINANCIAL_ENTITYID INT,
    @P_PROMOTION_TYPE VARCHAR(20),
    @P_DISCOUNT_PERCENTAGE DECIMAL(5,2),
    @P_MAX_REFUND DECIMAL(12,2),
    @P_START_DATE DATETIME,
    @P_END_DATE DATETIME,
    @P_AVAILABLE_QUANTITY INT,
    @P_STATUS BIT
AS
BEGIN
    INSERT INTO FINANCIALPROMOTIONS (
        FINANCIALENTITYID,
        PROMOTIONTYPE,
        DISCOUNTPERCENTAGE,
        MAXREFUND,
        STARTDATE,
        ENDDATE,
        AVAILABLEQUANTITY,
        STATUS,
        CREATEDAT
    )
    VALUES (
        @P_FINANCIAL_ENTITYID,
        @P_PROMOTION_TYPE,
        @P_DISCOUNT_PERCENTAGE,
        @P_MAX_REFUND,
        @P_START_DATE,
        @P_END_DATE,
        @P_AVAILABLE_QUANTITY,
        @P_STATUS,
        GETDATE()
    );
END
