/****** Object:  StoredProcedure [dbo].[DELETE_MERCHANT_PROMOTION_PR]    Script Date: 7/7/2025 3:17:51 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- DELETE
ALTER PROCEDURE [dbo].[DELETE_MERCHANT_PROMOTION_PR]
    @P_PROMOTIONID INT
AS
BEGIN
    DELETE FROM MerchantPromotions
    WHERE PromotionID = @P_PROMOTIONID;
END
